import React from 'react'

const Home = () => {
  return (
    <section className='w-full mt-[10%] pl-[10%] pr-[27%]'>
        <p>Home Page</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi cupiditate amet sit, provident voluptatibus autem quaerat voluptate quae unde earum repellat expedita, similique obcaecati laboriosam suscipit cum corporis consequatur quibusdam?
        Distinctio ea beatae illum, adipisci est consequuntur quis laudantium perferendis cupiditate ullam nesciunt, enim animi amet quod deleniti quasi nostrum labore! Esse vel iste nesciunt suscipit vero eius hic illum.
        Eligendi officia eveniet magni accusamus dicta iure officiis culpa, consequatur dolor libero! Nostrum, itaque doloremque explicabo, inventore ipsum perspiciatis, saepe non enim error sequi omnis esse earum quae consectetur molestiae.
        Obcaecati aperiam error nulla! Vitae accusantium saepe possimus aliquam commodi provident at pariatur ratione sapiente inventore quam alias quidem animi, illo nam quis ex, eius officia accusamus iusto soluta deleniti!
        Et mollitia quo iure similique vel laboriosam delectus reprehenderit impedit voluptate, facere officiis perspiciatis necessitatibus, maiores est praesentium. Et, laboriosam earum! Amet, rerum blanditiis. Beatae sed suscipit ea voluptate facere.
        Ea enim, nostrum aut eius quae consequatur, error corrupti debitis, repellat fuga soluta! Iste vel nisi sit, culpa at fuga quos doloribus amet. Iure reprehenderit dolor, esse iste sequi voluptatum.
        Iusto id provident, dicta sit fuga sequi ex qui, illo repudiandae vero magnam placeat quas eaque numquam tempora earum corrupti dolor porro cum cumque quasi necessitatibus ullam consequatur minus? Temporibus.
        Sed adipisci maxime placeat suscipit voluptas repellat nemo mollitia. Explicabo minima similique sint, voluptatum sit eius, voluptatibus iusto obcaecati iure earum recusandae blanditiis unde porro fuga illum. Labore, iusto at.
        Nulla unde quibusdam voluptatibus quasi repudiandae neque exercitationem deserunt magnam dicta cumque ut, iste necessitatibus sequi officiis inventore quidem? Placeat architecto consectetur asperiores eligendi ea ducimus non suscipit odio repudiandae.
        Cupiditate incidunt minima illo aliquam harum deleniti saepe eaque ex fuga nisi quam animi voluptates sint, atque tempore, quaerat quo, voluptatem aperiam sequi! Quaerat, illo placeat consequatur aut reprehenderit incidunt.
        Beatae aspernatur veritatis ipsa temporibus enim aperiam, voluptatem recusandae, iure consequuntur sint repellendus amet. Harum, dolores distinctio doloribus ipsa nesciunt temporibus nam. Obcaecati impedit laborum ipsam! Fuga quisquam fugiat quo!
        Laudantium, dolorum modi quae aut quia expedita impedit non repellendus numquam repellat! Expedita, reprehenderit atque. Optio distinctio harum eveniet magni, fugiat, dolor, reiciendis fugit modi consectetur eaque similique quia nemo?
        Quo aliquam odio exercitationem neque eum maxime iure reprehenderit ad pariatur, nisi, repellendus aperiam expedita cupiditate aliquid consectetur quam dolore accusantium possimus debitis commodi. Amet officiis illum blanditiis nam ducimus!
        Sit nobis vitae cum minus laborum impedit accusantium voluptatibus ipsum ipsa soluta. Cum quibusdam nisi, officiis magnam repellendus doloribus magni corporis reiciendis a voluptatem repudiandae quisquam voluptatum asperiores corrupti atque?
        Tenetur reiciendis enim quos officia alias tempore, harum laudantium cumque in ipsa doloremque cum modi ipsum praesentium, ab, quo molestiae sint minus dignissimos. Aut, dolore illo magnam numquam nemo maiores.
        Explicabo blanditiis consectetur cumque consequatur excepturi, architecto quidem. Architecto delectus corrupti debitis similique deleniti, ex asperiores nesciunt reiciendis nulla accusantium quaerat optio dolores perspiciatis fugiat officia laboriosam, quo nam et!
        Voluptatem, accusamus vitae velit consequatur eaque voluptatum placeat magni laborum excepturi mollitia aut obcaecati porro inventore ipsum exercitationem odit dolorum sapiente nesciunt adipisci itaque recusandae officia modi. Aliquid, saepe ab.
        Omnis fugit quasi impedit vel nulla similique neque voluptatum error fuga deleniti veniam a, vero repellendus, ipsa dolorum. Facilis cupiditate quia necessitatibus vero dolor, velit omnis minima inventore temporibus totam.
        Deserunt repudiandae minima distinctio necessitatibus molestiae esse blanditiis vel, laboriosam quae, explicabo repellat ea officia corporis molestias! Quibusdam eveniet doloremque facilis, corporis placeat maxime! Hic maxime reiciendis vero ullam voluptates.
        Repudiandae, vero ab consequuntur eum vel earum porro laboriosam sit aperiam reiciendis ad labore cum, quis totam mollitia nulla! Voluptatem velit, autem porro obcaecati eveniet saepe sunt. Voluptas, repudiandae non!
        Molestias fugit exercitationem ipsam rem! Incidunt nostrum quasi perspiciatis iusto facilis sapiente porro dolorum tempore amet vero illo rem asperiores tempora suscipit at, fugiat ut ex quos deserunt praesentium quia.
        Laborum hic similique quidem libero impedit aspernatur explicabo aperiam corporis, cupiditate soluta. Laudantium consequuntur, veritatis est enim sit aut in, repellendus laborum, hic incidunt reprehenderit! Excepturi, deserunt? Hic, nesciunt nemo!
        Suscipit magni rem ab tenetur qui, accusamus asperiores dolor reprehenderit ducimus? Ullam cupiditate dolorum distinctio explicabo doloribus natus molestias recusandae quam earum voluptate, assumenda ipsam ipsum repudiandae rem nobis ducimus!
        Est error explicabo expedita aliquam quaerat hic minus optio repellat quae sequi dolorem ipsum molestias, qui, omnis, modi praesentium voluptatem? Esse at quidem qui id ex fugit libero ipsum et!
        Minus animi iste necessitatibus odit alias repudiandae molestiae praesentium, natus voluptatem recusandae excepturi fugiat culpa accusantium aliquam consequuntur quos quae provident libero possimus vero voluptates nobis dolore nihil. Dolore, veniam?
        Voluptas delectus veniam id eos incidunt est blanditiis molestiae a, tempore quis ex itaque ratione placeat maxime autem perspiciatis, aliquam at ad non dolore! Illo illum maiores ducimus nisi minima.
        Mollitia ipsa consectetur quod eveniet necessitatibus aperiam blanditiis esse possimus quia enim, harum maxime architecto eligendi, repellendus dolores. Vero explicabo nesciunt adipisci odio sunt temporibus repellat assumenda enim dignissimos autem?
        Quod expedita veniam reiciendis at tenetur quaerat non ratione aliquam explicabo quasi. Illum laboriosam nostrum maiores. Voluptas ipsam, repudiandae quasi animi quidem quas, nisi molestias porro quae culpa, laborum asperiores.
        Voluptates corporis doloremque autem cum, excepturi odio impedit dolorum aut placeat quam, eius similique, quos nulla tempore temporibus assumenda eaque. Suscipit id itaque vero perspiciatis nihil aliquid cum modi reiciendis.
        Totam cupiditate ducimus similique quia, eligendi est inventore quidem dolorem nobis, reprehenderit, delectus corrupti deleniti distinctio. Fugit ad delectus laboriosam eius, quis quam doloremque reprehenderit autem explicabo aut. Et, porro.
        Modi expedita laboriosam placeat autem molestias, illo officiis porro tenetur nemo corporis perferendis quaerat deserunt animi tempora inventore nam atque minima! Laborum porro, molestiae suscipit architecto laudantium explicabo officia error!
        Sequi excepturi incidunt dolorum distinctio nobis temporibus repellat, praesentium nesciunt minima voluptates asperiores natus? Quos a nam voluptas iste temporibus esse? Eaque asperiores sit, nihil impedit natus quaerat voluptatum numquam.
        Neque libero fuga aspernatur labore voluptas explicabo sapiente minus debitis numquam nesciunt quod, nemo eos dolor provident quas iure obcaecati, ratione ex eum iste adipisci perspiciatis, hic nisi cum? Rem?
        Est, necessitatibus tempore aliquid eveniet nihil inventore, aliquam tempora quas placeat facere dolorem a quo perspiciatis deserunt officiis veniam labore cumque ad corporis non fuga minima. Eos sed suscipit rem!
        Voluptate illo expedita quaerat tempora fugit culpa, placeat voluptatem nulla maxime quis sint laboriosam totam consequatur nam explicabo illum numquam earum. Molestias vitae tempora magni eum officia, eos esse animi!
        Error voluptate aliquid dolore, odio expedita rerum? Quod delectus voluptas doloremque quaerat facilis? Reiciendis maxime, unde tempora consequuntur natus velit magni provident amet labore ducimus laborum quos, ea voluptates eveniet.
        Autem deleniti sed, mollitia at numquam ullam eveniet debitis vero, iste est cumque? Nobis facere aut expedita voluptatem, aliquam quas in numquam esse saepe, tempora magnam iusto libero qui modi!
        Iste fugit quod atque nihil accusantium suscipit, doloribus earum eveniet vitae vel placeat tempore, voluptates ullam incidunt adipisci recusandae, autem obcaecati ratione maxime? Magnam quo reiciendis nesciunt provident corporis modi?
        Deserunt eveniet eum omnis assumenda nesciunt cum numquam sequi excepturi tenetur illum tempora odio, repellendus voluptas quas modi distinctio! Neque dignissimos quae possimus rem, assumenda tempora dolorem explicabo impedit odit!
        Velit, aliquam quidem consequatur facilis tenetur animi quasi mollitia sed dolorum. Odio, esse exercitationem? Numquam quibusdam id illum perspiciatis deserunt iste laudantium ipsam officia excepturi. Enim expedita aut et sed.
        Nulla ea corrupti eum! Ex odit ipsum iure iste modi nobis. Illum ea asperiores molestias hic aperiam, corporis iste eveniet voluptatum accusamus officiis sapiente aliquam, laborum porro, debitis ab temporibus!
        Cumque corrupti alias sequi impedit voluptates fugiat earum, animi, quae qui fuga quia eligendi cupiditate odit facere. Officia debitis ratione accusantium iure corrupti maxime, incidunt est quam, reprehenderit, placeat recusandae.
        Provident, nobis neque soluta dignissimos mollitia ratione placeat maiores natus ipsum consequatur vitae quod eveniet laboriosam iure sed quae modi, nemo velit perspiciatis, minus earum at? Harum ab enim alias.
        Modi omnis molestias, ducimus ab odio, voluptatem hic autem tempora nobis nisi quia facilis nostrum, reprehenderit amet debitis! Quos expedita reiciendis corrupti, illum accusamus laborum porro blanditiis quod voluptate quidem?
        At sint quis aspernatur asperiores iste expedita omnis perferendis modi sunt consequuntur aliquam repellat, quas error quae, dicta deserunt temporibus voluptatibus quia animi! Consectetur id earum, mollitia assumenda debitis nemo.
        Corporis placeat odio laboriosam ea sapiente iure vero eum voluptatum vitae adipisci excepturi, blanditiis deserunt consequuntur ipsam minima, reiciendis accusantium aliquam id similique! Expedita, accusamus distinctio sed minima saepe officiis?
        Delectus, porro ullam hic unde laudantium facere perspiciatis, impedit minus consequuntur quidem ipsam fugiat nam ab debitis modi praesentium explicabo quisquam? Sunt vel magni voluptatum dolor atque architecto eaque? Eaque!
        Laborum veniam error laboriosam, voluptas totam asperiores! Recusandae et rem aliquid ea, temporibus reprehenderit? Reiciendis facilis quia tenetur repellat eum hic magni illo similique. Saepe ipsa dolores impedit! Ratione, voluptatum.
        Quis, repellendus magni cumque ipsam neque a, odio porro necessitatibus quasi qui laudantium! Explicabo ipsa nesciunt, ratione minus itaque officiis eveniet! In molestias porro cupiditate aut possimus architecto sunt nostrum?
        Adipisci, praesentium. Pariatur, animi? Debitis odio velit voluptas omnis, soluta qui nam tenetur! Voluptatibus reprehenderit veniam ducimus quaerat vel animi sunt quae odio eos repellendus? Porro voluptates voluptas beatae eos.</p>
    </section>
  )
}

export default Home